
CREATE TABLE AMISDBA.EHEBRNMNT
(
    NMNT_DSMS_SN                NUMBER(22) NOT NULL,
    SAFE_MNGR_TYP_CD            VARCHAR2(4) NOT NULL,
    NMNT_DSMS_TRGET_CLSF_CD     VARCHAR2(4),
    NMNT_CHRG_TYP_CD            VARCHAR2(2),
    EMPNO                       VARCHAR2(7),
    COMP_NM                     VARCHAR2(400),
    TARGTER_NM                  VARCHAR2(100),
    NMNT_DT                     VARCHAR2(8) NOT NULL,
    DSMS_DT                     VARCHAR2(8),
    NMNT_DSMS_PROGRS_STAT_CD    VARCHAR2(4),
    NMNT_CONFM_DT               VARCHAR2(8),
    NMNT_CONFMR_NM              VARCHAR2(100),
    NMNT_AUTH_DT                VARCHAR2(8),
    NMNT_AUTH_NM                VARCHAR2(100),
    NMNT_AUTH_YN                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    DSMS_CONFM_DT               VARCHAR2(8),
    DSMS_CONFMR_NM              VARCHAR2(100),
    DSMS_AUTH_DT                VARCHAR2(8),
    DSMS_AUTH_NM                VARCHAR2(100),
    DSMS_AUTH_YN                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    REL_INSTT_NM                VARCHAR2(400),
    ACT_BASIS_CNTE              VARCHAR2(400),
    RMRK                        VARCHAR2(4000),
    QLCR_NO                     VARCHAR2(20),
    QLCR_VLPR_DT                VARCHAR2(8),
    FRST_ENTR_EMPNO             VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM               DATE NOT NULL,
    FINL_UPID_EMPNO             VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM               DATE NOT NULL
)
TABLESPACE TS_ERP_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHEBRNMNT
ON AMISDBA.EHEBRNMNT (NMNT_DSMS_SN) 
TABLESPACE TS_ERP_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHEBRNMNT
ADD CONSTRAINT PK_EHEBRNMNT PRIMARY KEY (NMNT_DSMS_SN);

GRANT SELECT ON AMISDBA.EHEBRNMNT TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHEBRNMNT.ACT_BASIS_CNTE IS '법률근거내용';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.COMP_NM IS '업체명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_AUTH_DT IS '해임승인일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_AUTH_NM IS '해임승인자성명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_AUTH_YN IS '해임승인여부';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_CONFMR_NM IS '해임확인자성명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_CONFM_DT IS '해임확인일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.DSMS_DT IS '해임일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.EMPNO IS '사번';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_AUTH_DT IS '선임승인일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_AUTH_NM IS '선임승인자성명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_AUTH_YN IS '선임승인여부';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_CHRG_TYP_CD IS '선임담당유형코드';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_CONFMR_NM IS '선임확인자성명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_CONFM_DT IS '선임확인일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_DSMS_PROGRS_STAT_CD IS '선임해임진행상태코드';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_DSMS_SN IS '선임해임일련번호';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_DSMS_TRGET_CLSF_CD IS '선임해임대상분류코드';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.NMNT_DT IS '선임일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.QLCR_NO IS '자격증번호';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.QLCR_VLPR_DT IS '자격증유효기간일자';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.REL_INSTT_NM IS '관련기관명';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.RMRK IS '특기사항';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.SAFE_MNGR_TYP_CD IS '안전관리자유형코드';
COMMENT ON COLUMN AMISDBA.EHEBRNMNT.TARGTER_NM IS '대상자성명';
COMMENT ON TABLE AMISDBA.EHEBRNMNT IS '안전관리자선해임내역';

CREATE PUBLIC SYNONYM EHEBRNMNT
FOR AMISDBA.EHEBRNMNT;