
CREATE TABLE AMISDBA.EHSHRBARR
(
    ACCID_DCLAR_NO              VARCHAR2(12) NOT NULL,
    ACCID_DCLAR_RCEP_DIV_CD     VARCHAR2(4) NOT NULL,
    ACCID_NM                    VARCHAR2(400) NOT NULL,
    ACCID_OCCUR_DTM             DATE NOT NULL,
    BLOD_EXPO_ACCID_LOC_USE_CD  VARCHAR2(4) NOT NULL,
    BLOD_EXPO_ACCID_SITE_CD     VARCHAR2(4),
    BLOD_EXPO_ACCID_TYP_CD      VARCHAR2(4),
    BLOD_EXPO_ACCID_CRCS_CD     VARCHAR2(4),
    EMP_EXPO_CRCS_RSN           VARCHAR2(4000),
    ACCID_DAMG_DGREE_CD         VARCHAR2(4),
    EXPO_USE_UTENSL_CD          VARCHAR2(4),
    CSBD_INFO_PA                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CSBD_NM                     VARCHAR2(100),
    PATNO                       VARCHAR2(8),
    CSBD_SEX_CD                 VARCHAR2(1),
    CSBD_AGE                    NUMBER(10),
    CSBD_MDDP_CD                VARCHAR2(3),
    CSBD_WARD_CD                VARCHAR2(5),
    CSBD_DIAG_NM                VARCHAR2(400),
    HIV_EXPO_YN                 VARCHAR2(1) DEFAULT 'N' NOT NULL,
    SYPH_EXPO_YN                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    ETC_DSS_EXPO_YN             VARCHAR2(1) DEFAULT 'N' NOT NULL,
    ETC_DSS_EXPO_CNTE           VARCHAR2(400) DEFAULT NULL,
    EXAM_TKACT_NEED_YN          VARCHAR2(1) DEFAULT 'N' NOT NULL,
    OPAD_MDEX_YN                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    MDCT_NEED_YN                VARCHAR2(1) DEFAULT 'N' NOT NULL,
    LTR_TKACT_NEED_YN           VARCHAR2(1) DEFAULT 'N' NOT NULL,
    TKACT_FINSH_YN              VARCHAR2(1) DEFAULT 'N' NOT NULL,
    TKACT_LOC_CD                VARCHAR2(4),
    TKACT_FINSH_DTM             DATE,
    TKACT_FINSH_EMPNO           VARCHAR2(7),
    RMRK                        VARCHAR2(4000),
    FRST_ENTR_EMPNO             VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM               DATE NOT NULL,
    FINL_UPID_EMPNO             VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM               DATE NOT NULL
)
TABLESPACE TS_ERP_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHSHRBARR
ON AMISDBA.EHSHRBARR (ACCID_DCLAR_NO,ACCID_DCLAR_RCEP_DIV_CD) 
TABLESPACE TS_ERP_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHSHRBARR
ADD CONSTRAINT PK_EHSHRBARR PRIMARY KEY (ACCID_DCLAR_NO,ACCID_DCLAR_RCEP_DIV_CD);

GRANT SELECT ON AMISDBA.EHSHRBARR TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHSHRBARR.ACCID_DAMG_DGREE_CD IS '사고손상정도코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ACCID_DCLAR_NO IS '사고신고번호';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ACCID_DCLAR_RCEP_DIV_CD IS '사고신고접수구분코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ACCID_NM IS '사고명';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ACCID_OCCUR_DTM IS '사고발생일시';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.BLOD_EXPO_ACCID_CRCS_CD IS '혈액노출사고경위코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.BLOD_EXPO_ACCID_LOC_USE_CD IS '혈액노출사고장소사용코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.BLOD_EXPO_ACCID_SITE_CD IS '혈액노출사고부위코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.BLOD_EXPO_ACCID_TYP_CD IS '혈액노출사고유형코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_AGE IS '원인체나이';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_DIAG_NM IS '원인체진단명';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_INFO_PA IS '원인체정보유무';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_MDDP_CD IS '원인체진료과코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_NM IS '원인체명';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_SEX_CD IS '원인체성별코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.CSBD_WARD_CD IS '원인체병동코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.EMP_EXPO_CRCS_RSN IS '직원노출경위사유';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ETC_DSS_EXPO_CNTE IS '기타질환노출내용';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.ETC_DSS_EXPO_YN IS '기타질환노출여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.EXAM_TKACT_NEED_YN IS '검사조치필요여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.EXPO_USE_UTENSL_CD IS '노출사용기구코드';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.HIV_EXPO_YN IS 'HIV노출여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.LTR_TKACT_NEED_YN IS '추후조치필요여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.MDCT_NEED_YN IS '투약필요여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.OPAD_MDEX_YN IS '외래진료여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.PATNO IS '병원등록번호';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.RMRK IS '특기사항';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.SYPH_EXPO_YN IS '매독노출여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.TKACT_FINSH_DTM IS '조치완료일시';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.TKACT_FINSH_EMPNO IS '조치완료사번';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.TKACT_FINSH_YN IS '조치완료여부';
COMMENT ON COLUMN AMISDBA.EHSHRBARR.TKACT_LOC_CD IS '조치장소코드';
COMMENT ON TABLE AMISDBA.EHSHRBARR IS '혈액감염사고신고접수결과내역';

CREATE PUBLIC SYNONYM EHSHRBARR
FOR AMISDBA.EHSHRBARR;