
CREATE TABLE AMISDBA.EHCHRCDIP
(
    EHS_PLAN_MANAGE_SN      NUMBER(22) NOT NULL,
    EHS_DTL_PLAN_MANAGE_SN  NUMBER(22) NOT NULL,
    IMPV_SN                 NUMBER(22) NOT NULL,
    INCMPL_SCHM             VARCHAR2(4000) NOT NULL,
    IMPV_CNTP_CNTE          VARCHAR2(4000) NOT NULL,
    RMRK                    VARCHAR2(4000),
    FRST_ENTR_EMPNO         VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM           DATE NOT NULL,
    FINL_UPID_EMPNO         VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM           DATE NOT NULL
)
TABLESPACE TS_ERP_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHCHRCDIP
ON AMISDBA.EHCHRCDIP (EHS_PLAN_MANAGE_SN,EHS_DTL_PLAN_MANAGE_SN,IMPV_SN) 
TABLESPACE TS_ERP_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHCHRCDIP
ADD CONSTRAINT PK_EHCHRCDIP PRIMARY KEY (EHS_PLAN_MANAGE_SN,EHS_DTL_PLAN_MANAGE_SN,IMPV_SN);

GRANT SELECT ON AMISDBA.EHCHRCDIP TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHCHRCDIP.EHS_DTL_PLAN_MANAGE_SN IS 'EHS세부계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.EHS_PLAN_MANAGE_SN IS 'EHS계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.IMPV_CNTP_CNTE IS '개선대책내용';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.IMPV_SN IS '개선일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.INCMPL_SCHM IS '미비사항';
COMMENT ON COLUMN AMISDBA.EHCHRCDIP.RMRK IS '특기사항';
COMMENT ON TABLE AMISDBA.EHCHRCDIP IS '훈련미비사항개선계획내역';

CREATE PUBLIC SYNONYM EHCHRCDIP
FOR AMISDBA.EHCHRCDIP;