
CREATE TABLE AMISDBA.EHCHDCDSC
(
    EHS_PLAN_MANAGE_SN      NUMBER(22) NOT NULL,
    EHS_DTL_PLAN_MANAGE_SN  NUMBER(22) NOT NULL,
    CIRCUM_BHVR_KNACK_SN    NUMBER(22) NOT NULL,
    MANAGE_DEPT_CD          VARCHAR2(4),
    MANAGE_UNIT_CD          VARCHAR2(4),
    SORT_SEQ                NUMBER(10) NOT NULL,
    RMRK                    VARCHAR2(4000),
    FRST_ENTR_EMPNO         VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM           DATE NOT NULL,
    FINL_UPID_EMPNO         VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM           DATE NOT NULL,
    SCEN_CIRCUM_CD          VARCHAR2(4),
    SCEN_CIRCUM_NM          VARCHAR2(100),
    DSCP_TYP_CD             VARCHAR2(3),
    DSCP_TYP_NM             VARCHAR2(60),
    CIRCUM_BHVR_KNACK_NM    VARCHAR2(400),
    BHVR_TM                 VARCHAR2(6),
    USR_EMPNO               VARCHAR2(7)
)
TABLESPACE TS_ERP_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHCHDCDSC
ON AMISDBA.EHCHDCDSC (EHS_PLAN_MANAGE_SN,EHS_DTL_PLAN_MANAGE_SN,CIRCUM_BHVR_KNACK_SN) 
TABLESPACE TS_ERP_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHCHDCDSC
ADD CONSTRAINT PK_EHCHDCDSC PRIMARY KEY (EHS_PLAN_MANAGE_SN,EHS_DTL_PLAN_MANAGE_SN,CIRCUM_BHVR_KNACK_SN);

GRANT SELECT ON AMISDBA.EHCHDCDSC TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHCHDCDSC.BHVR_TM IS '행동시각';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.CIRCUM_BHVR_KNACK_NM IS '상황행동요령명';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.CIRCUM_BHVR_KNACK_SN IS '상황행동요령일련번호';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.DSCP_TYP_CD IS '훈련유형코드';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.DSCP_TYP_NM IS '훈련유형명';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.EHS_DTL_PLAN_MANAGE_SN IS 'EHS세부계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.EHS_PLAN_MANAGE_SN IS 'EHS계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.MANAGE_DEPT_CD IS '관리부서코드';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.MANAGE_UNIT_CD IS '관리UNIT코드';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.RMRK IS '특기사항';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.SCEN_CIRCUM_CD IS '시나리오상황코드';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.SCEN_CIRCUM_NM IS '시나리오상황명';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.SORT_SEQ IS '정렬순서';
COMMENT ON COLUMN AMISDBA.EHCHDCDSC.USR_EMPNO IS '담당자사번';
COMMENT ON TABLE AMISDBA.EHCHDCDSC IS '재난대비시나리오상세';

CREATE PUBLIC SYNONYM EHCHDCDSC
FOR AMISDBA.EHCHDCDSC;