
CREATE TABLE AMISDBA.EHEBMCDCI
(
    DSCP_TYP_CD     VARCHAR2(3) NOT NULL,
    DSCP_TYP_NM     VARCHAR2(60) NOT NULL,
    MANAGE_DEPT_CD  VARCHAR2(4),
    MANAGE_UNIT_CD  VARCHAR2(4),
    SORT_SEQ        NUMBER(10) NOT NULL,
    USE_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    FRST_ENTR_EMPNO VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM   DATE NOT NULL,
    FINL_UPID_EMPNO VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM   DATE NOT NULL
)
TABLESPACE TS_MST_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHEBMCDCI
ON AMISDBA.EHEBMCDCI (DSCP_TYP_CD) 
TABLESPACE TS_MST_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHEBMCDCI
ADD CONSTRAINT PK_EHEBMCDCI PRIMARY KEY (DSCP_TYP_CD);

GRANT SELECT ON AMISDBA.EHEBMCDCI TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHEBMCDCI.DSCP_TYP_CD IS '훈련유형코드';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.DSCP_TYP_NM IS '훈련유형명';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.MANAGE_DEPT_CD IS '관리부서코드';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.MANAGE_UNIT_CD IS '관리UNIT코드';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.SORT_SEQ IS '정렬순서';
COMMENT ON COLUMN AMISDBA.EHEBMCDCI.USE_YN IS '사용여부';
COMMENT ON TABLE AMISDBA.EHEBMCDCI IS '위기대응훈련유형기본';

CREATE PUBLIC SYNONYM EHEBMCDCI
FOR AMISDBA.EHEBMCDCI;