

CREATE OR REPLACE FUNCTION AMISDBA.FN_EH_CDNM
(
  R_EHS_MANAGE_UPR_CD        IN     VARCHAR2
, R_EHS_MANAGE_CD            IN     VARCHAR2
) 
RETURN VARCHAR2
IS

  S_EHS_MANAGE_CD_NM         EHEBMMNCD.EHS_MANAGE_CD_NM%TYPE     DEFAULT ' ';
BEGIN
 
   SELECT /*+ SQLID=FN_EH_CDNM.SQL_01 */
         EHS_MANAGE_CD_NM
    INTO S_EHS_MANAGE_CD_NM
    FROM EHEBMMNCD
   WHERE EHS_MANAGE_UPR_CD     = R_EHS_MANAGE_UPR_CD
     AND EHS_MANAGE_CD         = R_EHS_MANAGE_CD ;
 
 RETURN S_EHS_MANAGE_CD_NM;
EXCEPTION
  WHEN OTHERS THEN
    RETURN ' ';

END FN_EH_CDNM;
/

GRANT EXECUTE ON AMISDBA.FN_EH_CDNM TO RL_AMIS_RO;