
CREATE TABLE AMISDBA.EHCHRCDCL
(
    EHS_PLAN_MANAGE_SN      NUMBER(22) NOT NULL,
    EHS_DTL_PLAN_MANAGE_SN  NUMBER(22) NOT NULL,
    CIRCUM_BHVR_KNACK_SN    NUMBER(22) NOT NULL,
    SN                      NUMBER(22) NOT NULL,
    BHVR_KNACK_CNTE         VARCHAR2(1000) NOT NULL,
    BHVR_TM                 VARCHAR2(6),
    USR_EMPNO               VARCHAR2(7),
    SORT_SEQ                NUMBER(10) NOT NULL,
    RMRK                    VARCHAR2(4000),
    FRST_ENTR_EMPNO         VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM           DATE NOT NULL,
    FINL_UPID_EMPNO         VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM           DATE NOT NULL
)
TABLESPACE TS_ERP_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHCHRCDCL
ON AMISDBA.EHCHRCDCL
(
    EHS_PLAN_MANAGE_SN,
    EHS_DTL_PLAN_MANAGE_SN,
    CIRCUM_BHVR_KNACK_SN,
    SN
) 
TABLESPACE TS_ERP_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHCHRCDCL
ADD CONSTRAINT PK_EHCHRCDCL PRIMARY KEY (EHS_PLAN_MANAGE_SN,EHS_DTL_PLAN_MANAGE_SN,CIRCUM_BHVR_KNACK_SN,SN);

GRANT SELECT ON AMISDBA.EHCHRCDCL TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHCHRCDCL.BHVR_KNACK_CNTE IS '행동요령내용';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.BHVR_TM IS '행동시각';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.CIRCUM_BHVR_KNACK_SN IS '상황행동요령일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.EHS_DTL_PLAN_MANAGE_SN IS 'EHS세부계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.EHS_PLAN_MANAGE_SN IS 'EHS계획관리일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.RMRK IS '특기사항';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.SN IS '일련번호';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.SORT_SEQ IS '정렬순서';
COMMENT ON COLUMN AMISDBA.EHCHRCDCL.USR_EMPNO IS '담당자사번';
COMMENT ON TABLE AMISDBA.EHCHRCDCL IS '훈련체크리스트내역';

CREATE PUBLIC SYNONYM EHCHRCDCL
FOR AMISDBA.EHCHRCDCL;