CREATE TABLE AMISDBA.EHEBMCDSC
(
    SCEN_CIRCUM_CD  VARCHAR2(4) NOT NULL,
    DSCP_TYP_CD     VARCHAR2(3) NOT NULL,
    SCEN_NM         VARCHAR2(400) NOT NULL,
    SORT_SEQ        NUMBER(10) NOT NULL,
    USE_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    FRST_ENTR_EMPNO VARCHAR2(7) NOT NULL,
    FRST_ENTR_DTM   DATE NOT NULL,
    FINL_UPID_EMPNO VARCHAR2(7) NOT NULL,
    FINL_UPDT_DTM   DATE NOT NULL
)
TABLESPACE TS_MST_D
INITRANS 5
STORAGE
(
    INITIAL 64K
    NEXT 1M
)
NOCOMPRESS;

CREATE UNIQUE INDEX AMISDBA.PK_EHEBMCDSC
ON AMISDBA.EHEBMCDSC (SCEN_CIRCUM_CD,DSCP_TYP_CD) 
TABLESPACE TS_MST_X
STORAGE
(
    INITIAL 64K
    NEXT 1M
);

ALTER TABLE AMISDBA.EHEBMCDSC
ADD CONSTRAINT PK_EHEBMCDSC PRIMARY KEY (SCEN_CIRCUM_CD,DSCP_TYP_CD);

GRANT SELECT ON AMISDBA.EHEBMCDSC TO RL_AMIS_RO;

COMMENT ON COLUMN AMISDBA.EHEBMCDSC.DSCP_TYP_CD IS '훈련유형코드';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.FINL_UPDT_DTM IS '최종수정일시';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.FINL_UPID_EMPNO IS '최종수정자사번';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.FRST_ENTR_DTM IS '최초입력일시';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.FRST_ENTR_EMPNO IS '최초입력자사번';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.SCEN_CIRCUM_CD IS '시나리오상황코드';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.SCEN_NM IS '시나리오명';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.SORT_SEQ IS '정렬순서';
COMMENT ON COLUMN AMISDBA.EHEBMCDSC.USE_YN IS '사용여부';
COMMENT ON TABLE AMISDBA.EHEBMCDSC IS '위기대응시나리오상황기본';

CREATE PUBLIC SYNONYM EHEBMCDSC
FOR AMISDBA.EHEBMCDSC;